### PR TITLE
Updated question message for clarity.

### LINKED ISSUE #117: Update language
Change from:

"Bingo! Got it. I will remind the team that your vacation will take place between Tue Mar 20 2018 and Wed Mar 21 2018. Is that alright?"

to:

"Bingo! Got it. I will remind the team that your first day of vacation will be Tue Mar 20 2018 and your last day of vacation will be Thu Mar 23 2018. Is that alright?"

Reasoning: More clarity in the wording as to when you'll actually be back. This was requested from a company using it.

### PR DESCRIPTION
**Pull request by rmariuzzo**
Fixes #117.

### CODE REVIEW

**Comment by ryanchartrand** [comment]
@rmariuzzo Thanks for helping out! One thing we have to do here is get our language crystal clear. The bot asks "What day will you be back?" when collecting endDate, which means if we are reporting "and  your last day of vacation will be..." then it would be endDate - 1 :) 

Let's update the text to instead be more accurate:

``` your first day of vacation will be {{vars.startDate.fancy}} and you will return on {{vars.endDate.fancy}}```

**Comment by rmariuzzo** [comment]
@ryanchartrand I was a little bit naive and blind as I thought it was just a simple text replacement. And it is a text replacement, however I should have spend a few seconds analyzing the sense of it.

I have updated this PR with the changes requested.

**Comment by ryanchartrand** [comment]
Looks great! @jacekelgda can you review?

**Comment by jacekelgda** [comment]
Looks good +1

**Review by jacekelgda — APPROVED** [review]

**Pull request merged**
